[package]
name = "symb"
version = "0.0.1"
edition = "2018"
description = "Runtime symbolic computation"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "^0.10"